version: '3'
services:

    nginx:
        container_name: nginx
        build: ./nginx
        image: test/nginx
        restart: always
        ports:
          - "60080:80"
        extra_hosts:
          - "host.docker.internal:host-gateway"
        volumes:
          - ./django:/docker-server/seraph-web
          - ./log:/var/log/nginx
        depends_on:
          - django
        environment: 
          - TZ=Asia/Seoul

    django:
        container_name: django
        build: ./django
        image: test/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        environment: 
          - TZ=Asia/Seoul
        volumes:
          - ./django:/docker-server/seraph-web
          - ./log:/var/log/uwsgi